name: capsnet-env
channels:
    - https://conda.anaconda.org/menpo
    - conda-forge
dependencies:
    - python==3.5.4
    - numpy
    - matplotlib
    - jupyter
    - opencv3
    - pillow
    - scikit-learn
    - scikit-image
    - scipy
    - h5py
    - seaborn
    - pandas
    - imageio
    - pip:
        - tensorflow-gpu==1.3
        - asyncio
        - tqdm
        - ruamel.yaml
